TODO:
- implement action -b of wmctrl with property names "sticky", "above" and "below"
- provide decoration
- layout-cycling and storing of current layout
- little dmenu-wrapper
- implement xwinpp-tagging-action
- give option to decide, on which desktop a region should be placed
- "professional" error handling
- "professional" value checking
- introduce a command to decrease and increase number of windows in a specific region
- if region change its size, then this should have an effect on region b
- revise split-functions: determine empty space
- revise sed and grep code and try to translate it into bash code
- correct the english
- insert picture in the readme
- give much more comments in the scripts
- reimplement action size and move
- rename all variables and then use set "$ set -o posix ; set" with another grep script
- give all subcommands long options, when using directly
- checking for requiered software
- think about to integrate xwinpp into xwinreg as subscript

DONE:
- revise frame-handling
- color border of active frame, region and window (independent of gtk theme etc.)
    - we are using a "visual bell" instead
- cycling of windows in a specific region
- variables in the temp file, which are not imported from xwinpp, should be stored in an associative array instead using several sorted indexed arrays to avoid eval
- create new main manpage and one for every action
- give an example in doc, how to use xwinreg with openbox
- include some example commands in doc
- create a readme to show what layouts make sense
- figure out, how to install with install
- insert copyright head into every script
