.\" Manpage of xwinreg-cycle/v0.1.0.1
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v2.0
.\" generated with Ronn/v0.7.3
.
.TH "XWINREG\-CYCLE" "1" "2014-06-10" "0.1.0.1" "User Manual"
.
.SH "NAME"
\fBxwinreg\-cycle\fR \- cycle order of regions or windows\.
.
.SH "XWINREG"
Part of \fBxwinreg\fR(1)\.
.
.SH "SYNOPSIS"
xwinreg\-cycle [\-T] (\-h|\-r|\-v) \-d [\-j|\-k|\-w]
.
.SH "REQUIREMENT"
GNU bash, grep, sed, xprop
.
.SH "DESCRIPTION"
\fBxwinreg\-cycle\fR(1) reads variables inside a Tmp File and prepares cycling of specified regions or windows\. The modified variables will be written to the Tmp File\. After that, \fBxwinreg\-layout\fR(1) can perform its layouts with new geos and/or new order of x window ids\.
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR \fIYDIREC\fR
Specify direction of cycling\.
.
.TP
\fB\-h\fR
Display a short help\.
.
.TP
\fB\-j\fR
Used with options \fB\-w\fR and \fB\-r\fR with more than one region as argument (Example: \fB\-r 1,3\fR)\. Cycling takes place between regions; without this option, windows are only cycled inside specific regions\.
.
.TP
\fB\-k\fR
Cycle windows and layout\-actions, but keep region position\. Without this option, region positions are cycled (together with windows and layout\-actions)\.
.
.TP
\fB\-r\fR \fIREG\fR
Select, which regions should be processed\.
.
.TP
\fB\-T\fR \fIFILE\fR
Specify a nonregular Tmp file\.
.
.TP
\fB\-v\fR
Print current version of \fBxwinreg\-cycle\fR(1)\.
.
.TP
\fB\-w\fR
Indicate that windows (not regions) should be processed\.
.
.SH "ARGUMENTS"
.
.TP
\fIFILE\fR
Regular file or named pipe\.
.
.TP
\fIREG\fR
Up to this sample: \fB1\fR or \fB1,3\fR or \fB1\-3\fR or \fB1,2\-3\fR\. Additional: \fBactive\fR or \fBall\fR\.
.
.TP
\fIYDIREC\fR
\fBclock\fR, \fBanticlock\fR or \fBreverse\fR\.
.
.SH "EXAMPLES"
.
.SH "ENVIROMENT"
.
.TP
\fITMPDIR\fR
By default, Tmp File will be written as \fBTMPDIR/xwinreg_default\.tmp\fR, otherwise as \fB/tmp/xwinreg_default\.tmp\fR\.
.
.TP
\fIXWINREG_TMP_FILE\fR
Specify this instead default setting and instead using \fIXWINREG_TMP_FILE\fR in a Conf File\.
.
.SH "BUGS & REQUESTS"
Report it on \fBhttps://github\.com/D630/xwinreg/issues\fR
.
.SH "LICENSE"
\fBxwinreg\-cycle\fR(1) is licensed with GNU GPLv3\. You should have received a copy of the GNU General Public License along with this program\. If not, see for more details \fBhttp://www\.gnu\.org/licenses/gpl\-3\.0\.html\fR\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBgrep\fR(1), \fBsed\fR(1), \fBx\fR(7), \fBxprop\fR(1), \fBxwinreg\fR(1), \fBxwinreg\-calculate\fR(1), \fBxwinreg\-close\fR(1), \fBxwinreg\-focus\fR(1), \fBxwinreg\-focus\-toggle\fR(1), \fBxwinreg\-hide\fR(1), \fBxwinreg\-id\fR(1), \fBxwinreg\-layout\fR(1), \fBxwinreg\-move\-to\-desk\fR(1)
