.\" Manpage of xwinreg-layout/v0.1.0.4
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v2.0
.\" generated with Ronn/v0.7.3
.
.TH "XWINREG\-LAYOUT" "1" "2014-06-14" "0.1.0.4" "User Manual"
.
.SH "NAME"
\fBxwinreg\-layout\fR \- build layouts inside arranged regions and fill them rule\-based with windows\.
.
.SH "XWINREG"
Part of \fBxwinreg\fR(1)\.
.
.SH "SYNOPSIS"
xwinreg\-layout (\-h|\-v)
.
.P
xwinreg\-layout [\-T] \-L \.\.\.
.
.P
xwinreg\-layout [\-T] (\-l \-A \-e \-g \-G \-r \-x) \.\.\.
.
.SH "REQUIREMENT"
bc, GNU bash, wmctrl
.
.SH "DESCRIPTION"
After processing of \fBxwinreg\-id\fR(1) and \fBxwinreg\-calculate\fR(1), \fBxwinreg\-layout\fR(1) reads their variables from a Tmp File and builds layouts in specified regions and fill them rule\-based with windows\. After layouting, the Tmp File will has been updated with new variables\. Without layout\-actions, \fBxwinreg\-layout\fR(1) just reads the Tmp File and reruns the last documented layout\.
.
.P
All layouting takes place in only one frame\. That one frame may have the geometry of the workspace or any other\. To work with more than one frame, you need to create more than one Tmp File\. See \fBxwinreg\-calculate\fR(1)\.
.
.SH "ACTIONS"
.
.TP
\fB\-l\fR
Build layout\. Specify the layout with options \fB\-r\fR, \fB\-x\fR, \fB\-A\fR, \fB\-e\fR, \fB\-G\fR and \fB\-g\fR\.
.
.TP
\fB\-L\fR \fIREGN\fR,\fIWINN\fR,\fILACT\fR,\fILENT\fR:\fIGRAV\fR,\fIGEO\fR
Write action \fB\-l\fR in shorthand\.
.
.SH "OPTIONS"
.
.TP
\fB\-A\fR \fILACT\fR
Specify, how a region should be filled with windows\.
.
.TP
\fB\-e\fR \fILENT\fR
Specify the entity of \fIGEO\fR\.
.
.TP
\fB\-g\fR \fIGEO\fR
Specify the geometry of a region\.
.
.TP
\fB\-G\fR \fIGRAV\fR
Specify the gravity of windows in a region\. If you are indecisive, use 0\.
.
.TP
\fB\-h\fR
Display a short help\.
.
.TP
\fB\-r\fR \fIREGN\fR
Specify, which region should be processed\.
.
.TP
\fB\-T\fR \fIFILE\fR
Specify a nonregular Tmp file\.
.
.TP
\fB\-v\fR
Print current version of \fBxwinreg\-layout\fR(1)\.
.
.TP
\fB\-x\fR \fIWINN\fR
Maximal number of windows a region should contain\.
.
.SH "ARGUMENTS"
.
.TP
\fIFILE\fR
Regular file or named pipe\.
.
.TP
\fIGEO\fR
\fIX\fR: Pixel x size specified by an integer\. \fIY\fR: Pixel y size specified by an integer\. \fIW\fR: Pixel width size specified by an integer\. \fIH\fR: Pixel height size specified by an integer\. \fIPRO\fR: Procent size specified by an integer\. \fIREGALIAS\fR: \fBnorthwest\fR, \fBnorth\fR, \fBnortheast\fR, \fBeast\fR, \fBsoutheast\fR, \fBsouth\fR, \fBsouthwest\fR or \fBwest\fR\. Samples: "\fIREGALIAS\fR", "\fIPRO\fR,\fIPRO\fR,\fIPRO\fR,\fIPRO\fR", "\fIX\fR,\fIY\fR,\fIW\fR,\fIH\fR"\.
.
.TP
\fIGRAV\fR
\fBnorthwest\fR, \fBnorth\fR, \fBnortheast\fR, \fBwest\fR, \fBcenter\fR, \fBeast\fR, \fBsouthwest\fR, \fBsouth\fR, \fBsoutheast\fR or \fBstatic\fR\. Additional: \fB[0\-10]\fR\.
.
.TP
\fILACT\fR
\fBmaximize\fR, \fBhorizontal\fR, \fBvertical\fR, \fBgrid\-horizontal\fR, \fBgrid\-vertical\fR, \fBgrid\-square\-horizontal\fR or \fBgrid\-square\-vertical\fR\.
.
.TP
\fILENT\fR
\fBalias\fR, \fBpx\fR or \fBpro\fR\.
.
.TP
\fIREGN\fR
Region number specified by an integer\.
.
.TP
\fIWINN\fR
Window number specified by an integer or \fBmax\fR\.
.
.SH "EXAMPLES"
xwinreg\-layout \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg\-layout \-L 1,max,grid\-horizontal,alias:0,all
.
.P
xwinreg\-layout \-L 1,max,grid\-square\-horizontal,alias:0,all
.
.P
xwinreg\-layout \-L 1,max,maximize,alias:0,all
.
.P
xwinreg\-layout \-L 1,1,maximize,alias:0,west \-L 2,max,horizontal,alias:0,east
.
.P
xwinreg\-layout \-L 1,1,maximize,alias:0,west \-L 2,1,maximize,alias:0,northeast \-L 3,max,vertical,alias:0,southeast
.
.SH "NOTES"
You can specify region aliases in a Conf File, which will be read by \fBxwinreg\-calculate\fR(1) and written to a Tmp File\. See section \fBCONFIGURATIONS\fR in its Manpage\.
.
.P
If you use action \fB\-l\fR, actually, the first option needs to be \fB\-r\fR\.
.
.SH "ENVIROMENT"
.
.TP
\fITMPDIR\fR
By default, Tmp File will be written as \fBTMPDIR/xwinreg_default\.tmp\fR, otherwise as \fB/tmp/xwinreg_default\.tmp\fR\.
.
.TP
\fIXWINREG_TMP_FILE\fR
Specify this instead default setting and instead using \fIXWINREG_TMP_FILE\fR in a Conf File\.
.
.SH "BUGS & REQUESTS"
Report it on \fBhttps://github\.com/D630/xwinreg/issues\fR
.
.SH "LICENSE"
\fBxwinreg\-layout\fR(1) is licensed with GNU GPLv3\. You should have received a copy of the GNU General Public License along with this program\. If not, see for more details \fBhttp://www\.gnu\.org/licenses/gpl\-3\.0\.html\fR\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBbc\fR(1), \fBwmctrl\fR(1), \fBx\fR(7), \fBxorg\fR(1), \fBxwinreg\fR(1), \fBxwinreg\-calculate\fR(1), \fBxwinreg\-close\fR(1), \fBxwinreg\-cycle\fR(1), \fBxwinreg\-focus\fR(1), \fBxwinreg\-focus\-toggle\fR(1), \fBxwinreg\-hide\fR(1), \fBxwinreg\-id\fR(1), \fBxwinreg\-move\-to\-desk\fR(1)
