.\" Manpage of xwinreg/v0.2.0.0
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v2.0
.\" generated with Ronn/v0.7.3
.
.TH "XWINREG" "1" "2014-06-14" "0.2.0.0" "User Manual"
.
.SH "NAME"
\fBxwinreg\fR \- organize X windows into regions and do tiling layouts\.
.
.SH "SYNOPSIS"
\fBxwinreg (\-h|\-v)\fR
.
.P
\fBxwinreg close [\-T] \-r\fR
.
.P
\fBxwinreg cycle [\-T] [\-w \-r] \-d (\-j|\-k|)\fR
.
.P
\fBxwinreg focus [\-T] \-r\fR
.
.P
\fBxwinreg focus\-toggle [\-T] \-d\fR
.
.P
\fBxwinreg hide [\-T] \-r \-A\fR
.
.P
\fBxwinreg \-I [\-C|\-T|\-n|\-N|\-a|\-1|\-2|\-3|\-4|\-5|\-6|\-7|\-8] (layout \-A \-e \-g \-G \-r \-x) \.\.\.\fR
.
.P
\fBxwinreg \-I [\-C|\-T|\-n|\-N|\-a|\-1|\-2|\-3|\-4|\-5|\-6|\-7|\-8] layout\-abbrev \.\.\.\fR
.
.P
\fBxwinreg move\-to\-desk [\-T] \-r \-D [\-W]\fR
.
.SH "REQUIREMENT"
bc, GNU bash, GNU grep, GNU sed, wmctrl, X, xprop, xwininfo, xwinpp
.
.SH "USE CASE"
You use a stacking window manager like \fBopenbox\fR(1), but sometimes you want to tile all windows without the mouse and arrange them in different "layouts"\.
.
.SH "DESCRIPTION"
\fBxwinreg\fR(1) is a bash shell script that acts like a stupid third party tiling application on Xorg\. It lets you organize X windows into frames and regions and then to build your own layouts in a simple way\. Therefore, \fBxwinreg\fR(1) uses \fBxwinpp\fR(1) to prepare a list of X window ids, and \fBwmctrl\fR(1) to interact with your EWMH/NetWM compatible X Window manager\. See section \fBCONCEPTION\fR in this Manpage\.
.
.P
Strictly speaking, \fBxwinreg\fR(1) is a bash shell script, that wraps up following scripts (see also their Manpages, how to use them directly without \fBxwinreg\fR(1) as wrapper):
.
.SS "xwinreg\-calculate(1) \- calculate frame geos\."
Just as \fBxwinreg\-id\fR(1), \fBxwinreg\-calculate\fR(1) is required for layouting with \fBxwinreg\-layout\fR(1)\. Its purpose is to set a frame relative to a workspace as scale base and to have base geometries; without that calculation \fBxwinreg\-layout\fR(1) is not able to arrange regions and fill those with windows\. All variables are written to a Temp File, and will then be processed in the course of layouting\. You can here also determine the number of rows and columns for grid layouting or specify a Conf File with variables and frame aliases\.
.
.P
In the wrapper script \fBxwinreg\fR(1) you may not call the calculation directly; it will be called, before you build layouts with action \fB\-l\fR and \fB\-L\fR\.
.
.SS "xwinreg\-close(1) \- close regions gracefully\."
\fBxwinreg\-close\fR(1) reads variables inside a Tmp File and closes specified regions\. After closing the Tmp File will be updated\.
.
.SS "xwinreg\-cycle(1) \- cycle order of regions or windows\."
\fBxwinreg\-cycle\fR(1) reads variables inside a Tmp File and prepares cycling of specified regions or windows\. The modified variables will be written to the Tmp File\. After that, \fBxwinreg\-layout\fR(1) can perform its layouts with new geos and/or new order of x window ids\.
.
.SS "xwinreg\-focus(1) \- focus all windows in specified regions\."
\fBxwinreg\-focus\fR(1) reads variables inside a Tmp File and focuses windows in specified regions\. Therefore, it switches to the desktop containing the windows, raises the windows, and gives them focus\. At the end, the active window will be focused again\. The Tmp File will not have an update\.
.
.SS "xwinreg\-focus\-toggle(1) \- toggle focus on windows in all regions\."
\fBxwinreg\-focus\-toggle\fR(1) reads a Tmp File with variables and changes the active window\. After focusing, the Tmp file will be updated\.
.
.SS "xwinreg\-hide(1) \- add or remove window property \'hidden\' in specified regions\."
\fBxwinreg\-hide\fR(1) reads variables in a Tmp File and modifies the hidden property of windows in specified regions\. The Tmp File is not updated after this action\.
.
.SS "xwinreg\-id(1) \- get prepared X window ids from xwinpp(1)\."
Just as \fBxwinreg\-calculate\fR(1), \fBxwinreg\-id\fR(1) is required for layouting with \fBxwinreg\-layout\fR(1)\. Its purpose is to read the ouput of \fBxwinpp\fR(1) and to create a Tmp File with its variables\.
.
.P
In the wrapper script \fBxwinreg\fR(1) you may not call \fBxwinreg\-id\fR(1) directly; it will be called, if you use the option \fB\-I\fR to indicate an Input File\.
.
.SS "xwinreg\-layout(1) \- build layouts inside arranged regions and fill them rule\-based with windows\."
After processing of \fBxwinreg\-id\fR(1) and \fBxwinreg\-calculate\fR(1), \fBxwinreg\-layout\fR(1) reads their variables from a Tmp File and builds layouts in specified regions and fill them rule\-based with windows\. After layouting, the Tmp File will has been updated with new variables\. Without layout\-actions, \fBxwinreg\-layout\fR(1) just reads the Tmp File and reruns the last documented layout\.
.
.P
All layouting takes place in only one frame\. That one frame may have the geometry of the workspace or any other\. To work with more than one frame, you need to create more than one Tmp File\. See \fBxwinreg\-calculate\fR(1)\.
.
.SS "xwinreg\-move\-to\-desk(1) \- move windows of specified regions to another desktop\."
\fBxwinreg\-move\-to\-desk\fR(1) reads variables of a Tmp File and moves windows to a desktop\. The Tmp File is not updated after that action\.
.
.SH "CONCEPTION"
\fBxwinpp\fR(1) reads a list with X window ids and does a preparing output with variables, which will be read by \fBxwinreg\fR(1)\. By using action \fBlayout\fR or \fBlayout\-abbrev\fR a layout is generated and all specified windows will be ordered\. In the course of layouting, a Tmp File with some variables is created\. Any other actions then need to access that Tmp File to work properly\. Only above layout actions must be used in combination with \fBxwinpp\fR(1); no windows to read are needed anymore\.
.
.P
The layout is set only one workarea\. Therefore, \fBxwinreg\fR(1) reads \fI_NET_WORKAREA\fR and determines a frame as scale base to have base geometry\. In this frame \fBxwinreg\fR(1) arranges numbered regions, which are filled rule\-based with the windows\. Windows are taken in list\-order; the first window is set as first window in the first region\. You can determine, how many windows a region should have (minimum is one; maximum is the number of imported windows)\. The windows will be split and positioned with following actions: maximize, vertical, horizontal, grid\-vertical, grid\-horizontal, grid\-square\-vertical, grid\-square\-horizontal\.
.
.P
In other words: all layouting takes place in one frame\. That one frame may have the geometry of the workspace or any other\. To work with more than one frame, you need to create more than one Tmp File\. See sections \fBNOTES\fR and \fBCONFIGURATION\fR in this Manpage\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR, \fB\-\-frame\-alias=\fR \fIFRAMEALIAS\fR
Instead of options \fB\-fx\fR, \fB\-fy\fR, \fB\-fw\fR and \fB\-fh\fR, specify an alias\. See section \fBCONFIGURATIONS\fR in this Manpage\.
.
.TP
\fB\-C\fR, \fB\-\-conf\-file=\fR \fIFILE\fR
Read variables from \fIFILE\fR\. See section \fBCONFIGURATIONS\fR in this Manpage\.
.
.TP
\fB\-fh\fR, \fB\-\-frame\-height=\fR \fIPX\fR
Specify the \fIHEIGHT\fR of the frame\.
.
.TP
\fB\-fw\fR, \fB\-\-frame\-width=\fR \fIPX\fR
Specify the \fIWIDTH\fR of the frame\.
.
.TP
\fB\-fx\fR, \fB\-\-frame\-x=\fR \fIPX\fR
Specify the left edge of the frame\.
.
.TP
\fB\-fy\fR, \fB\-\-frame\-y=\fR \fIPX\fR
Specify the top edge of the frame\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a short help\.
.
.TP
\fB\-I\fR, \fB\-\-input\-file=\fR \fIFILE\fR
Obtain output of \fBxwinpp\fR(1) from \fIFILE\fR\. If \fIFILE\fR is a hyphen, get output from \fBxwinpp\fR(1) by reading from standard input\.
.
.TP
\fB\-n\fR, \fB\-\-number\-of\-rows=\fR \fIINT\fR
Specify number of rows for grid layouting\.
.
.TP
\fB\-N\fR, \fB\-\-number\-of\-cols=\fR \fIINT\fR
Specify number of columns for grid layouting\.
.
.TP
\fB\-T\fR, \fB\-\-tmp\-file=\fR \fIFILE\fR
Before layouting, \fBxwinreg\fR(1) creates a Tmp File, whose variables are needed by all other actions to work with\. With this option you can specify a nonregular file\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print current version of \fBxwinreg\fR(1)\.
.
.TP
\fB\-wh\fR, \fB\-\-workarea\-height=\fR \fIPX\fR
Specify the \fIHEIGHT\fR of the workarea\.
.
.TP
\fB\-ww\fR, \fB\-\-workarea\-width=\fR \fIPX\fR
Specify the \fIWIDTH\fR of the workarea\.
.
.TP
\fB\-wx\fR, \fB\-\-workarea\-x=\fR \fIPX\fR
Specify the left edge of the workarea\.
.
.TP
\fB\-wy\fR, \fB\-\-workarea\-y=\fR \fIPX\fR
Specify the top edge of the workarea\.
.
.SH "SUBCOMNMANDS"
.
.SS "ACTIONS"
.
.TP
\fB\-c\fR, \fB\-\-close\fR
Close windows gracefully\. Specify this action with option \fB\-r\fR\.
.
.TP
\fB\-f\fR, \fB\-\-focus\fR
Switch to the desktop containing the windows, raise the windows, and give them focus\. At the end, focus the active window again\. Specify this action with option \fB\-r\fR\.
.
.TP
\fB\-H\fR, \fB\-\-hide\fR
Add or remove window property hidden\. Specify this action with option \fB\-r\fR and \fB\-A\fR\.
.
.TP
\fB\-l\fR, \fB\-\-layout\fR
Build layout and create Tmp File\. Specify the layout with options \fB\-r\fR, \fB\-x\fR, \fB\-A\fR, \fB\-e\fR, \fB\-G\fR and \fB\-g\fR\.
.
.TP
\fB\-L\fR, \fB\-\-layout\-abbrev\fR \fIREGN\fR,\fIWINN\fR,\fILACT\fR,\fILENT\fR:\fIGRAV\fR,\fIGEO\fR
Write action \fB\-l\fR in shorthand\.
.
.TP
\fB\-M\fR, \fB\-\-move\-to\-desk\fR
Move windows to another desktop\. Specify this action with options \fB\-r\fR, \fB\-D\fR and \fB\-W\fR\.
.
.TP
\fB\-o\fR, \fB\-\-focus\-toggle\fR
Tell \fBxwinreg\fR(1) to toggle focus on windows\. Specify this action with option \fB\-d\fR\.
.
.TP
\fB\-y\fR, \fB\-\-cycle\fR
Cycle order of regions or windows\. Specify this action with options \fB\-r\fR, \fB\-d\fR, \fB\-w\fR, \fB\-j\fR and \fB\-k\fR\.
.
.SS "OPTIONS"
.
.TP
\fB\-A\fR, \fB\-\-action=\fR ( \fIHACT\fR | \fILACT\fR )
Used with actions \fB\-l\fR and \fB\-L\fR to tell \fBxwinreg\fR(1), how a region should be filled with windows\. Used with action \fB\-H\fR to specify hide action\.
.
.TP
\fB\-d\fR, \fB\-\-direction=\fR ( \fIODIREC\fR | \fIYDIREC\fR )
Used with actions \fB\-o\fR and \fB\-y\fR\.
.
.TP
\fB\-D\fR, \fB\-\-desk=\fR \fIDESK\fR
Move windows to desktop \fIDESK\fR\.
.
.TP
\fB\-e\fR, \fB\-\-entity=\fR \fILENT\fR
Specify the entity of actions \fB\-l\fR and \fB\-L\fR\.
.
.TP
\fB\-g\fR, \fB\-\-geo=\fR \fIGEO\fR
Specify the geometry of actions \fB\-l\fR and \fB\-L\fR\.
.
.TP
\fB\-G\fR, \fB\-\-gravity=\fR \fIGRAV\fR
Used with actions \fB\-l\fR and \fB\-L\fR to specify the gravity\. If you are indecisive, use \fB0\fR\.
.
.TP
\fB\-j\fR, \fB\-\-join\fR
Used with action \fB\-y\fR and options \fB\-w\fR and \fB\-r\fR with more than one region as argument (Example: \fB\-r 1,3\fR)\. Cycling takes place between regions; without this option, windows are only cycled inside specific regions\.
.
.TP
\fB\-k\fR, \fB\-\-stack\fR
Used with action \fB\-y\fR to keep region position, but cycle windows and \fILACT\fR\. Without this option region positions are cycled (together with windows and \fILACT\fR)\.
.
.TP
\fB\-r\fR, \fB\-\-region=\fR ( \fIREG\fR | \fIREGN\fR )
Select, which regions should be processed\.
.
.TP
\fB\-w\fR, \fB\-\-window\fR
Used with actions \fB\-y\fR to indicate, that windows (not regions) should be processed\.
.
.TP
\fB\-W\fR, \fB\-\-switch\fR
Used with action \fB\-M\fR to switch to the desktop after moving\.
.
.TP
\fB\-x\fR, \fB\-\-maximum=\fR \fIWINN\fR
Maximal number of windows a region should contain\. Used with actions \fB\-l\fR and \fB\-L\fR\.
.
.SH "ARGUMENTS"
.
.TP
\fIDESK\fR
\fBcurr\fR or relative to the current desktop \fBnext\fR or \fBpreview\fR\. To specify a desktop number (starts at 0) use the prefix \fBi:\fR; a desktop name is prefixed with \fBs:\fR\. Examples: \fBi:1\fR; \fBs:web\fR; \fB"s:some stuff"\fR\.
.
.TP
\fIFILE\fR
Regular file or named pipe\.
.
.TP
\fIFRAMEALIAS\fR
\fBnorthwest\fR, \fBnorth\fR, \fBnortheast\fR, \fBeast\fR, \fBsoutheast\fR, \fBsouth\fR, \fBsouthwest\fR or \fBwest\fR\. You can create your own aliases in a Conf File or overwrite those defaults\.
.
.TP
\fIGEO\fR
\fIX\fR: Pixel x size specified by an integer\. \fIY\fR: Pixel y size specified by an integer\. \fIW\fR: Pixel width size specified by an integer\. \fIH\fR: Pixel height size specified by an integer\. \fIPRO\fR: Procent size specified by an integer\. \fIREGALIAS\fR: \fBnorthwest\fR, \fBnorth\fR, \fBnortheast\fR, \fBeast\fR, \fBsoutheast\fR, \fBsouth\fR, \fBsouthwest\fR or \fBwest\fR\. Samples: "\fIREGALIAS\fR", "\fIPRO\fR,\fIPRO\fR,\fIPRO\fR,\fIPRO\fR", "\fIX\fR,\fIY\fR,\fIW\fR,\fIH\fR"\.
.
.TP
\fIGRAV\fR
\fBnorthwest\fR, \fBnorth\fR, \fBnortheast\fR, \fBwest\fR, \fBcenter\fR, \fBeast\fR, \fBsouthwest\fR, \fBsouth\fR, \fBsoutheast\fR or \fBstatic\fR\. Additional: \fB[0\-10]\fR\.
.
.TP
\fIHACT\fR
\fBadd\fR or \fBremove\fR\.
.
.TP
\fIINT\fR
Default is \fB2\fR\.
.
.TP
\fILACT\fR
\fBmaximize\fR, \fBhorizontal\fR, \fBvertical\fR, \fBgrid\-horizontal\fR, \fBgrid\-vertical\fR, \fBgrid\-square\-horizontal\fR or \fBgrid\-square\-vertical\fR\.
.
.TP
\fILENT\fR
\fBalias\fR, \fBpx\fR or \fBpro\fR\.
.
.TP
\fIODIREC\fR
\fBnext\fR or \fBpreview\fR\.
.
.TP
\fIPX\fR
Pixel size specified by an integer\.
.
.TP
\fIREG\fR
Up to this sample: \fB1\fR or \fB1,3\fR or \fB1\-3\fR or \fB1,2\-3\fR\. Additional: \fBactive\fR or \fBall\fR\.
.
.TP
\fIREGN\fR
Region number specified by an integer\.
.
.TP
\fIWINN\fR
Window number specified by an integer or \fBmax\fR\.
.
.TP
\fIYDIREC\fR
\fBclock\fR, \fBanticlock\fR or \fBreverse\fR\.
.
.SH "EXAMPLES"
.
.SS "close"
xwinreg close \-r active
.
.P
xwinreg close \-T ${Home}/tmp/xwinreg\.tmp \-r 2
.
.SS "cycle"
xwinreg cycle \-w \-r all \-d clock
.
.P
xwinreg cycle \-w \-r active \-d anticlock
.
.P
xwinreg cycle \-w \-r 1,3 \-d clock
.
.P
xwinreg cycle \-w \-r 1,3 \-d clock \-j
.
.P
xwinreg cycle \-d anticlock
.
.P
xwinreg cycle \-k \-d clock
.
.SS "focus"
xwinreg focus \-r active
.
.P
xwinreg focus \-T ${Home}/tmp/xwinreg\.tmp \-r 2
.
.SS "focus\-toggle"
xwinreg \-o \-d preview
.
.P
xwinreg \-o \-T ${Home}/tmp/xwinreg\.tmp \-d next
.
.SS "hide"
xwinreg hide \-r active \-A remove
.
.P
xwinreg hide \-T ${Home}/tmp/xwinreg\.tmp \-r 2 \-A add
.
.SS "layout"
xwinpp \-F \./list \-P 1 \-p | xwinreg \-I \- \-L 1,max,horizontal,alias:0,all
.
.P
xwinpp \-F \./list \-P 1 \-p | xwinreg \-I \- \-T ${Home}/tmp/xwinreg\.tmp \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \- \-L 1,max,horizontal,alias:0,all < <(xwinpp \-F \./list \-P 1 \-p)
.
.P
xwinreg \-I <(xwinpp \-F \./list \-P 1 \-p) \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-wx 0 \-wy 0 \-ww 1680 \-wh 1049 \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-fw 0 \-fh 0 \-fx 840 \-fy 524 \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-C ${Home}/\.config/xwinreg/xwinreg\.conf \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-C ${Home}/\.config/xwinreg/xwinreg\.conf \-a new_frame_alias \-L 1,max,horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,max,grid\-horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,max,grid\-square\-horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-n 4 \-N 4 \-L 1,max,grid\-square\-horizontal,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,max,maximize,alias:0,all
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,1,maximize,alias:0,west \-L 2,max,horizontal,alias:0,east
.
.P
xwinreg \-I \./output\-of\-xwinpp \-L 1,1,maximize,alias:0,west \-L 2,1,maximize,alias:0,northeast \-L 3,max,vertical,alias:0,southeast
.
.SS "move\-to\-desk"
xwinreg \-M \-r active \-D next \-W
.
.P
xwinreg \-M \-r 2 \-D curr
.
.P
xwinreg \-M \-r active \-D i:1 \-W
.
.P
xwinreg \-M \-r active \-D s:internet \-W
.
.SH "NOTES"
If no workarea geometry is set, \fI_NET_WORKAREA\fR is used\.
.
.P
Currently, window decoration is not considered\.
.
.P
If no frame geometry is set, \fI_NET_WORKAREA\fR is used as frame\. Every new frame needs its own Tmp File\. In other words: all layouting takes place in one frame\. You can specify another Tmp File with option \fB\-T\fR, or you may create several Conf Files\. See section \fBCONFIGURATIONS\fR in this Manpage\.
.
.P
Options on command line overwrites variables in a Conf File\.
.
.P
You can specify region aliases in a Conf File, which will be read by action \fBl\fR and \fBL\fR and written to a Tmp File\. See section \fBCONFIGURATIONS\fR in this Manpage\.
.
.P
If you use action \fB\-l\fR, actually, the first option needs to be \fB\-r\fR\.
.
.SH "CONFIGURATIONS"
By default, \fBxwinreg\fR(1) needs no Conf File, because all important geometries will be calculated in the script\. You can also use the relating options on command line\. So, only use a Conf File, if you want to work with several frames (and several Tmp Files are needed) or if you need to set own aliases for frame and region geometries\. Along with this programm comes an exemplary Conf File\. Specify a Conf File with option \fB\-C\fR or use \fIXWINREG_CONF_FILE\fR\. You can set following parameters:
.
.TP
enviroment variables
\fBXWINREG_TMP_FILE=\fIFILE\fR\fR; \fBXWINREG_INPUT_FILE=\fIFILE\fR\fR
.
.TP
normal scalar variables
\fBworkarea_x=\fIPX\fR\fR; \fBworkarea_y=\fIPX\fR\fR; \fBworkarea_width=\fIPX\fR\fR; \fBworkarea_height=\fIPX\fR\fR; \fBframe_x=\fIPX\fR\fR; \fBframe_y=\fIPX\fR\fR; \fBframe_width=\fIPX\fR\fR; \fBframe_height=\fIPX\fR\fR; \fBrow_number=\fIINT\fR\fR; \fBcol_number=\fIINT\fR\fR
.
.TP
associativ array variables
You can use it with above variables\. You need to set them inside a function called \fB__xwr_xwinreg_calculate_calculating_frame_alias\fR respectively \fB__xwr_xwinreg_calculate_calculating_region_alias\fR and declare it with \fBdeclare \-gA frames\fR respectively \fBdeclare \-gA regions\fR: \fBframes[\fIALIAS\fR]="\fIX\fR \fIY\fR \fIW\fR \fIH\fR"\fR; \fBregions[\fIALIAS\fR]="\fIX\fR \fIY\fR \fIW\fR \fIH\fR"\fR
.
.SH "ENVIROMENT"

.
.TP
\fITMPDIR\fR
By default, Tmp File will be written as \fBTMPDIR/xwinreg_default\.tmp\fR, otherwise as \fB/tmp/xwinreg_default\.tmp\fR\.
.
.TP
\fIXWINREG_CONF_FILE\fR
Use this instead of option \fB\-C\fR, if you want to use a Conf File\.
.
.TP
\fIXWINREG_INPUT_FILE\fR
Use this instead of option \fB\-I\fR\.
.
.TP
\fIXWINREG_TMP_FILE\fR
Specify this instead default setting and instead using \fIXWINREG_TMP_FILE\fR in a Conf File\.
.
.SH "BUGS & REQUESTS"
Report it on \fBhttps://github\.com/D630/xwinreg/issues\fR
.
.SH "TODO"
See file \fBTODO\fR, which comes along with this programm\.
.
.SH "LICENSE"
\fBxwinreg\fR(1) is licensed with GNU GPLv3\. You should have received a copy of the GNU General Public License along with this program\. If not, see for more details \fBhttp://www\.gnu\.org/licenses/gpl\-3\.0\.html\fR\.
.
.SH "CHRONICLE"
First version (0\.1\.0\.0) was finished on: 2014\-02\-10\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBbc\fR(1), \fBgrep\fR(1), \fBsed\fR(1), \fBwmctrl\fR(1), \fBx\fR(7), \fBxorg\fR(1), \fBxprop\fR(1), \fBxwininfo\fR(1), \fBxwinpp\fR(1), \fBxwinreg\fR(1), \fBxwinreg\-calculate\fR(1), \fBxwinreg\-close\fR(1), \fBxwinreg\-cycle\fR(1), \fBxwinreg\-focus\fR(1), \fBxwinreg\-focus\-toggle\fR(1), \fBxwinreg\-hide\fR(1), \fBxwinreg\-id\fR(1), \fBxwinreg\-layout\fR(1), \fBxwinreg\-move\-to\-desk\fR(1)
