.\" Manpage of xwinreg-move-to-desk/v0.1.0.2
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v2.0
.\" generated with Ronn/v0.7.3
.
.TH "XWINREG\-MOVE\-TO\-DESK" "1" "2014-06-10" "0.1.0.2" "User Manual"
.
.SH "NAME"
\fBxwinreg\-move\-to\-desk\fR \- move windows of specified regions to another desktop\.
.
.SH "XWINREG"
Part of \fBxwinreg\fR(1)\.
.
.SH "SYNOPSIS"
xwinreg\-move\-to\-desk [\-T] (\-h|\-r|\-v) \-D [\-W]
.
.SH "REQUIREMENT"
GNU bash, grep, wmctrl, xprop
.
.SH "DESCRIPTION"
\fBxwinreg\-move\-to\-desk\fR(1) reads variables of a Tmp File and moves windows to a desktop\. The Tmp File is not updated after that action\.
.
.SH "OPTIONS"
.
.TP
\fB\-D\fR \fIDESK\fR
Move windows to desktop \fIDESK\fR
.
.TP
\fB\-h\fR
Display a short help\.
.
.TP
\fB\-r\fR \fIREG\fR
Select, which regions should be processed\.
.
.TP
\fB\-T\fR \fIFILE\fR
Specify a nonregular Tmp file\.
.
.TP
\fB\-v\fR
Print current version of \fBxwinreg\-move\-to\-desk\fR(1)\.
.
.TP
\fB\-W\fR
Switch to \fIDESK\fR after moving\.
.
.SH "ARGUMENTS"
.
.TP
\fIDESK\fR
\fBcurr\fR or relative to the current desktop \fBnext\fR or \fBpreview\fR\. To specify a desktop number (starts at 0) use the prefix \fBi:\fR; a desktop name is prefixed with \fBs:\fR\. Examples: \fBi:1\fR; \fBs:web\fR; \fB"s:some stuff"\fR\.
.
.TP
\fIFILE\fR
Regular file or named pipe\.
.
.TP
\fIREG\fR
Up to this sample: \fB1\fR or \fB1,3\fR or \fB1\-3\fR or \fB1,2\-3\fR\. Additional: \fBactive\fR or \fBall\fR\.
.
.SH "EXAMPLES"
xwinreg\-move\-to\-desk \-r active \-D next \-W
.
.P
xwinreg\-move\-to\-desk \-r 2 \-D curr
.
.P
xwinreg\-move\-to\-desk \-r active \-D i:1 \-W
.
.P
xwinreg\-move\-to\-desk \-r active \-D s:internet \-W
.
.SH "ENVIROMENT"
.
.TP
\fITMPDIR\fR
By default, Tmp File will be written as \fBTMPDIR/xwinreg_default\.tmp\fR, otherwise as \fB/tmp/xwinreg_default\.tmp\fR\.
.
.TP
\fIXWINREG_TMP_FILE\fR
Specify this instead default setting and instead using \fIXWINREG_TMP_FILE\fR in a Conf File\.
.
.SH "BUGS & REQUESTS"
Report it on \fBhttps://github\.com/D630/xwinreg/issues\fR
.
.SH "LICENSE"
\fBxwinreg\-move\-to\-desk\fR(1) is licensed with GNU GPLv3\. You should have received a copy of the GNU General Public License along with this program\. If not, see for more details \fBhttp://www\.gnu\.org/licenses/gpl\-3\.0\.html\fR\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBgrep\fR(1), \fBwmctrl\fR(1), \fBx\fR(7), \fBxprop\fR(1), \fBxwinreg\fR(1), \fBxwinreg\-calculate\fR(1), \fBxwinreg\-close\fR(1), \fBxwinreg\-cycle\fR(1), \fBxwinreg\-focus\fR(1), \fBxwinreg\-focus\-toggle\fR(1), \fBxwinreg\-hide\fR(1), \fBxwinreg\-id\fR(1), \fBxwinreg\-layout\fR(1)
