.\" Manpage of xwinreg-id/v0.1.0.1
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v2.0
.\" generated with Ronn/v0.7.3
.
.TH "XWINREG\-ID" "1" "2014-06-10" "0.1.0.1" "User Manual"
.
.SH "NAME"
\fBxwinreg\-id\fR \- calculate frame geos\.
.
.SH "XWINREG"
Part of \fBxwinreg\fR(1)\.
.
.SH "SYNOPSIS"
xwinreg\-id [\-T] (\-h|\-I|\-v)
.
.SH "REQUIREMENT"
GNU bash, grep, xwinpp
.
.SH "DESCRIPTION"
Just as \fBxwinreg\-calculate\fR(1), \fBxwinreg\-id\fR(1) is required for layouting with \fBxwinreg\-layout\fR(1)\. Its purpose is to read the ouput of \fBxwinpp\fR(1) and to create a Tmp File with its variables\.
.
.P
In the wrapper script \fBxwinreg\fR(1) you may not call \fBxwinreg\-id\fR(1) directly; it will be called, if you use the option \fB\-I\fR to indicate an Input File\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Display a short help\.
.
.TP
\fB\-I\fR \fIFILE\fR
Obtain output of \fBxwinpp\fR(1) from \fIFILE\fR\. If \fIFILE\fR is a hyphen, get output from \fBxwinpp\fR(1) by reading from standard input\.
.
.TP
\fB\-T\fR \fIFILE\fR
Specify a nonregular Tmp file\.
.
.TP
\fB\-v\fR
Print current version of \fBxwinreg\-id\fR(1)\.
.
.SH "ARGUMENTS"
.
.TP
\fIFILE\fR
Regular file or named pipe\.
.
.SH "EXAMPLES"
xwinpp \-F \./list \-P 1 \-p | xwinreg\-id \-I \-
.
.P
xwinpp \-F \./list \-P 1 \-p | xwinreg\-id \-I \- \-T ${Home}/tmp/xwinreg\.tmp
.
.P
xwinreg\-id \-I \- < <(xwinpp \-F \./list \-P 1 \-p)
.
.P
xwinreg\-id \-I \./output\-of\-xwinpp
.
.P
xwinreg\-id \-I <(xwinpp \-F \./list \-P 1 \-p)
.
.SH "ENVIROMENT"
.
.TP
\fITMPDIR\fR
By default, Tmp File will be written as \fBTMPDIR/xwinreg_default\.tmp\fR, otherwise as \fB/tmp/xwinreg_default\.tmp\fR\.
.
.TP
\fIXWINREG_TMP_FILE\fR
Specify this instead default setting and instead using \fIXWINREG_TMP_FILE\fR in a Conf File\.
.
.TP
\fIXWINREG_INPUT_FILE\fR
Use this instead of option \-I\.
.
.SH "BUGS & REQUESTS"
Report it on \fBhttps://github\.com/D630/xwinreg/issues\fR
.
.SH "LICENSE"
\fBxwinreg\-id\fR(1) is licensed with GNU GPLv3\. You should have received a copy of the GNU General Public License along with this program\. If not, see for more details \fBhttp://www\.gnu\.org/licenses/gpl\-3\.0\.html\fR\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBgrep\fR(1), \fBx\fR(7), \fBxwinpp\fR(1), \fBxwinreg\fR(1), \fBxwinreg\-calculate\fR(1), \fBxwinreg\-close\fR(1), \fBxwinreg\-cycle\fR(1), \fBxwinreg\-focus\fR(1), \fBxwinreg\-focus\-toggle\fR(1), \fBxwinreg\-hide\fR(1), \fBxwinreg\-layout\fR(1), \fBxwinreg\-move\-to\-desk\fR(1)
