#!/usr/bin/env bash

__check_variables_input()
{
    if [[ $1 =~ ^(desk_curr|win_active|win_active_frame_extents|win_active_tags|win_number|desk_select|win_active_geo_x_y|win_active_geo_w_h|win_xid|win_geo_x_y|win_geo_w_h|win_frame_extents|win_tags)=.*$ ]]
    then
        eval "$1"
    else
        { echo "Irregular variable inside input." >&2 ; exit 1 ; }
    fi
}
