#!/usr/bin/env bash

__help()
{
    __src_script usage
    printf "
$(__usage)

OPTIONS
-------
    OPTION                    ARG
    ------                    ---
    -F,  --file=              <FILE> or hyphen (-)
    -C,  --conf-file=         <FILE>
    -T,  --tmp-file=          <FILE>
    -n,  --number-of-rows=    <INT>
    -N,  --number-of-cols=    <INT>
    -a,  --frame-alias=       <FRAMEALIAS>
    -fx, --frame-x=           <PX>
    -fy, --frame-y=           <PX>
    -fw, --frame-width=       <PX>
    -fh, --frame-height=      <PX>
    -wx, --workarea-x=        <PX>
    -wy, --workarea-y=        <PX>
    -ww, --workarea-width=    <PX>
    -wh, --workarea-height=   <PX>
    -h,  --help
    -v,  --version

SUBCOMMANDS
-----------
    ACTION                    REQUIRED
    ------                    --------
    -c,  --close              <REG>
    -H,  --hide               <REG>
    -U,  --unhide             <REG>
    -f,  --focus              <REG>
    -o,  --toggle-focus       <ODIREC>
    -M,  --move-to-desk       <REG> <DESK> -W
    -y,  --cycle              <REG> <YDIREC> -w -k -j
    -l,  --layout             <REGN> <WINN> <SPLIT> <LENT> <GRAV> <GEO>

    ACTION                    ARG
    ------                    ---
    -L,  --layout-abbrev=     <REGN>,<WINN>,<SPLIT>,<LENT>:<GRAV>,<GEO>

    OPTION                    ARG
    ------                    ---
    -r,  --region=            ( <REG> | <REGN> )
    -d,  --direction=         ( <ODIREC> | <YDIREC>  )
    -D,  --desk=              <DESK>
    -e,  --entity=            <LENT>
    -g,  --geo=               <GEO>
    -x,  --maximum=           <WINN>
    -G,  --gravity=           <GRAV>
    -A,  --action=            <SPLIT>
    -w,  --window
    -W,  --switch
    -k,  --stack
    -j,  --join

ARGUMENTS
---------
    <FILE>          Regular file or named pipe.
    <INT>           Default is '2'.
    <FRAMEALIAS>    'northwest', 'north', 'northeast', 'east',
                    'southeast', 'south', 'southwest' or 'west'.
    <PX>            Pixel size specified by an integer.
    <REG>           Up to this sample: '1', '1,3', '1-3' or '1,2-3'.
                    Additional: 'active' or 'all'.
    <REGN>          Region number specified by an integer.
    <ODIREC>        'next' or 'preview'.
    <YDIREC>        'clock', 'anticlock' or 'reverse'.
    <DESK>          'curr' or relative to the current desktop 'next' or
                    'preview'. To specify a desktop number (starts at 0)
                    use the prefix 'i:'; a desktop name is prefixed with
                    's:'. Examples: 'i:1'; 's:web'; '\"s:some stuff\"'.
    <LENT>          'alias', 'px' or 'pro'.
    <REF>           'window', 'region' or 'frame'.
    <WINN>          Window number specified by an integer or 'max'.
    <GRAV>          'northwest', 'north', 'northeast', 'west', 'center',
                    'east', 'southwest', 'south', 'southeast' or
                    'static'. Additional: '[0-10]'.
    <SPLIT>         'maximize', 'horizontal', 'vertical',
                    'grid-horizontal', 'grid-vertical',
                    'grid-square-horizontal' or 'grid-square-vertical'.
    <GEO>
                    <X>        Pixel x size specified by an integer.
                    <Y>        Pixel y size specified by an integer.
                    <W>        Pixel width size specified by an integer.
                    <H>        Pixel height size specified by an integer.
                    <PRO>      Procent size specified by an integer.
                    <REGALIAS> 'northwest', 'north', 'northeast','east',
                               'southeast', 'south', 'southwest' or
                               'west'.
                    Samples:
                               '<REGALIAS>',
                               '<PRO>,<PRO>,<PRO>,<PRO>',
                               '<X>,<Y>,<W>,<H>'.
"
}
