#!/usr/bin/env bash

__grid_horizontal()
{
    # Adapted. See for more details http://forum.ubuntuusers.de/topic/wmtiler-fuer-floating-wm-s/
    declare \
            i= \
            win= \
            x= \
            y= \
            w= \
            h= \
            normal_row_windows= \
            bottom_row_windows= \
            windows_not_in_bottom_row= \
            x_org= \
            normal_row_width= \
            bottom_row_width=
            current_row= \
            current_row_windows=

    x=$1
    y=$2
    w=$3
    h=$4

    normal_row_windows=$((win_region_number/row_number))
    bottom_row_windows=$((normal_row_windows+win_region_number%row_number))
    windows_not_in_bottom_row=$((win_region_number-bottom_row_windows))
    x_org=$x
    h=$((h/row_number))
    normal_row_width=$(((w/normal_row_windows)-normal_row_windows))
    bottom_row_width=$(((w/bottom_row_windows)-normal_row_windows))

    current_row=1

    for ((i=0 , current_row_windows=0 ; i <= win_region_number-1 ; i++ , current_row_windows++))
    do
        ((current_row < row_number)) &&
        {
            ((current_row_windows == normal_row_windows)) &&
            {
                ((current_row++))
                if ((current_row == row_number))
                then
                    x=$x_org
                    y=$((y+h))
                    w=$bottom_row_width
                else
                    current_row_windows=0
                fi
            }
            ((current_row_windows == 0)) && x=$x_org && w=$normal_row_width && { ((current_row != 1)) && y=$((y+h)) ; }
        }

        win=${win_xid[i]}
        __do_wmctrl

        __store_region
        x=$((x+w))
    done
}
