#!/usr/bin/env bash

__check_args()
{
    declare o
    if [[ ! $OPTARG = -* ]]
    then
        for o
        do
            declare -g "$o"
        done
    else
        { echo "Option -${opt} requires an argument." >&2 ; exit 1 ; }
    fi
}
