#!/usr/bin/env bash

__check_region_selection()
{
    case $region_selection in
        all)
                mapfile -t layout_numbers < <(printf '%s\n' "${layout[@]%%,*}")
                layout_selection=(${layout[@]})
                ;;
        active)
                __get_win_active
                __get_region_active
                layout_numbers=(${region_active[@]})
                layout_selection=(${layout[layout_numbers[0]-1]})
                ;;
        *)
                [[ $region_selection =~ (-|,|[[:digit:]]) ]] &&
                {
                    for region_number in $(__parse_region "$region_selection")
                    do
                        layout_numbers+=($region_number)
                        layout_selection+=(${layout[region_number-1]})
                    done
                }
                ;;
    esac

    mapfile -t layout_numbers < <(__order_num_asc_array "${layout_numbers[@]}")
    mapfile -t layout_selection < <(__order_num_asc_array "${layout_selection[@]}")
}
