#!/usr/bin/env bash

__grid_vertical()
{
    # Adapted. See for more details http://forum.ubuntuusers.de/topic/wmtiler-fuer-floating-wm-s/

    normal_column_windows=$((win_region_number/col_number))
    right_column_windows=$((normal_column_windows+win_region_number%col_number))
    windows_not_in_bottom_column=$((win_region_number-right_column_windows))
    y_org=$y
    w=$((w/col_number))
    normal_column_height=$((h/normal_column_windows))
    right_column_height=$((h/right_column_windows))

    current_column=1
    for ((i=0 , current_column_windows=0 ; i <= win_region_number-1 ; i++ , current_column_windows++))
    do
        ((current_column < col_number)) &&
        {
            ((current_column_windows == normal_column_windows)) &&
            {
                ((current_column++))
                if ((current_column == col_number))
                then
                    x=$((x+w))
                    y=$y_org
                    h=$right_column_height
                else
                    current_column_windows=0
                fi
            }
            ((current_column_windows == 0)) && y=$y_org && h=$normal_column_height && { ((current_column != 1)) && x=$((x+w)) ; }
        }

        win=${win_xid[i]}
        __do_wmctrl

        __store_region
        y=$((y+h))
    done
}
