#!/usr/bin/env bash

__calculating()
{
    # Check, if geo of workarea is manually set; if not, we use __NET_WORKAREA instead.
    declare -ga workarea=()
    read -a workarea < <(xprop -root -notype _NET_WORKAREA) &&
            workarea=(${workarea[@]//,}) &&
            workarea=(${workarea[@]:2})
    declare -g workarea_x=${workarea_x:-${workarea[0]}} \
               workarea_y=${workarea_y:-${workarea[1]}} \
               workarea_w=${workarea_width:-${workarea[2]}} \
               workarea_h=${workarea_height:-${workarea[3]}}

    # Check, if frame aliases have been set in a Conf File.
    if declare -f __calculating_frame_alias > /dev/null
    then
        __calculating_frame_alias
    else
        declare -gA frames
    fi

    # We use these aliases for frame geo. We also check, if aliases with same names have been set manually.
    #declare -gA frame
    frames[northwest]=${frames[northwest]:-$workarea_x $workarea_y $((workarea_w/2)) $((workarea_h/2))}
    frames[north]=${frames[north]:-$workarea_x $workarea_y $workarea_w $((workarea_h/2))}
    frames[northeast]=${frames[northeast]:-$((workarea_x+workarea_w/2)) $workarea_y $((workarea_w/2)) $((workarea_h/2))}
    frames[east]=${frames[east]:-$((workarea_x+workarea_w/2)) $workarea_y $((workarea_w/2)) $workarea_h}
    frames[southeast]=${frames[southeast]:-$((workarea_x+workarea_w/2)) $((workarea_y+workarea_h/2)) $((workarea_w/2)) $((workarea_h/2))}
    frames[south]=${frames[south]:-$workarea_x $((workarea_y+workarea_h/2)) $workarea_w $((workarea_h/2))}
    frames[southwest]=${frames[southwest]:-$workarea_x $((workarea_y+workarea_h/2)) $((workarea_w/2)) $((workarea_h/2))}
    frames[west]=${frames[west]:-$workarea_x $workarea_y $((workarea_w/2)) $workarea_h}
    frames[all]=${frames[all]:-$workarea_x $workarea_y $workarea_w $workarea_h}

    if [[ $frame_alias ]]
    then
        declare -a frame_geo=(${frames[$frame_alias]})
        declare -g frame_x=${frame_x:-${frame_geo[0]}} \
                   frame_y=${frame_y:-${frame_geo[1]}} \
                   frame_w=${frame_width:-${frame_geo[2]}} \
                   frame_h=${frame_height:-${frame_geo[3]}}
    else
        declare -g frame_x=${frame_x:-$workarea_x} \
                   frame_y=${frame_y:-$workarea_y} \
                   frame_w=${frame_width:-$workarea_w} \
                   frame_h=${frame_height:-$workarea_h}
    fi

    # To simplify matters, we alias frames geo to x,y,w and h.
    declare -g x=$frame_x \
               y=$frame_y \
               w=$frame_w \
               h=$frame_h

    # Check, if region aliases have been set in a Conf File.
    if declare -f __calculating_region_alias > /dev/null
    then
        __calculating_region_alias
    else
        declare -gA regions
    fi

    # We use these aliases for regions geo. We also check, if aliases with same names have been set manually.
    regions[northwest]=${regions[northwest]:-$x $y $((w/2)) $((h/2))}
    regions[north]=${regions[north]:-$x $y $w $((h/2))}
    regions[northeast]=${regions[northeast]:-$((x+w/2)) $y $((w/2)) $((h/2))}
    regions[east]=${regions[east]:-$((x+w/2)) $y $((w/2)) $h}
    regions[southeast]=${regions[southeast]:-$((x+w/2)) $((y+h/2)) $((w/2)) $((h/2))}
    regions[south]=${regions[south]:-$x $((y+h/2)) $w $((h/2))}
    regions[southwest]=${regions[southwest]:-$x $((y+h/2)) $((w/2)) $((h/2))}
    regions[west]=${regions[west]:-$x $y $((w/2)) $h}
    regions[all]=${regions[all]:-$x $y $w $h}

    # Here we declare row and column number, which are needed to perform grid layouting.
    declare -g row_number=${row_number:-2} \
               col_number=${col_number:-2}

    unset -v \
            workarea_width \
            workarea_height \
            frame_width \
            frame_height
}
