#!/usr/bin/env bash

__mktmp()
{
    fgrep -v -e "$vars_base" < <(set -o posix ; set) |
    egrep -v -e "^vars_base=" \
             -e "^BASH_REMATCH=" \
             -e "^OPTIND=" \
             -e "^REPLY=" \
             -e "^BASH_LINENO=" \
             -e "^BASH_SOURCE=" \
             -e "^FUNCNAME=" \
    > "$file_tmp"

    unset -v vars_base
}
