#!/usr/bin/env bash

__horizontal()
{
    declare \
            i= \
            win= \
            x=$1 \
            y=$2 \
            w=$3 \
            h=$4

    h=$((h/win_region_number))

    for ((i=0 ; i <= win_region_number-1 ; i++))
    do
        win=${win_xid[i]}
        __do_wmctrl
        __store_region
        y=$((y+h))
    done
}
