#!/usr/bin/env bash

__comm_array()
{
    declare \
            arg= \
            counter= \
            element_array_1= \
            element_array_2= \
            skip= \

    declare -a \
               array_1=() \
               array_2=()

    { (($#)) && counter=1 ; } || return 1

    for arg
    do
        [[ $arg == -- ]] && ((counter++))
    done

    for ((i=1 ; i <= $counter ; i++))
    do
        while [[ $# -gt 0 && $1 != -- ]]
        do
            eval "array_${i}+=( "$1" )"
            shift 1
        done
        [[ $1 == -- ]] && shift 1
    done

    for element_array_1 in "${array_1[@]}"
    do
        for element_array_2 in "${array_2[@]}"
        do
            [[ $element_array_1 == $element_array_2 ]] && { skip=1 ; break ; }
        done
        ((skip)) || printf '%s\n' "$element_array_1"
        skip=
    done
}
