#!/usr/bin/env bash

__build_layout()
{
    [[ ! $@ =~ not_available && $# -eq 6 ]] &&
    {
        layout[${1}:region_number]=$1
        layout[${1}:win_number_maximum]=$2
        layout[${1}:layout_action]=$3
        layout[${1}:entity_region]=$4
        layout[${1}:gravity]=${5}
        layout[${1}:region_geo]=${6}

        ((reg_number++))
    }
}
